language: c
dist: trusty

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      libsysfs-dev
      libxml2
      libxml2-dev
      libssl-dev
      libcurl3-dev

script: ./autogen.sh && ./configure && make && make check

after_script: 
        - pwd && cat tests/rngtesturandom.sh.log && cat tests/rngtestzero.sh.log
