language: c
dist: trusty

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      libsysfs-dev
      libxml2
      libxml2-dev
      libssl-dev
      libcurl3-dev

script: ./autogen.sh && ./configure && make

